# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags:
    - integration


linters:
  disable-all: true
  enable:
    #    - errcheck
    #    - goimports
    - revive
    - govet
    - staticcheck


issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "exported (const|type|method|function) (.+) should have comment or be unexported"
