name: CI
on:
  - push
  - pull_request

jobs:
  branch:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') && github.event_name != 'pull_request' }}
    steps:
      - name: Set up Go v1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint
        uses: golangci/golangci-lint-action@v2

      - name: Test
        run: make test-cov

      - name: Build
        run: make build

      - name: Publish code coverage report
        if: contains(github.ref, 'main')
        uses: codecov/codecov-action@v2
        with:
          files: out/coverage.out

  pr:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') && github.event_name == 'pull_request' }}
    steps:
      - name: Set up Go v1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint
        uses: golangci/golangci-lint-action@v2

      - name: Test
        run: make test-cov

      - name: Build
        run: make build

      - name: Publish code coverage report
        uses: codecov/codecov-action@v2
        with:
          files: out/coverage.out
